(define (problem labworkflow-p04)
 (:domain labworkflow)
 (:objects s1 s2 s3 - sample r1 r2 r3 - reagent)
 (:init
  (sample_available s1)
  (sample_available s2)
  (sample_available s3)
  (reagent_available r1)
  (reagent_available r2)
  (reagent_available r3)
 )
 (:goal (and
  (reagent_logged r1)
  (analysis_done s1 r1)
  (reagent_logged r2)
  (analysis_done s2 r2)
  (reagent_logged r3)
  (analysis_done s3 r3)
 ))
)
