(define (problem labworkflow-p06)
 (:domain labworkflow)
 (:objects s1 s2 s3 s4 s5 - sample r1 r2 r3 r4 r5 - reagent)
 (:init
  (sample_available s1)
  (sample_available s2)
  (sample_available s3)
  (sample_available s4)
  (sample_available s5)
  (reagent_available r1)
  (reagent_available r2)
  (reagent_available r3)
  (reagent_available r4)
  (reagent_available r5)
 )
 (:goal (and
  (reagent_logged r1)
  (analysis_done s1 r1)
  (reagent_logged r2)
  (analysis_done s2 r2)
  (reagent_logged r3)
  (analysis_done s3 r3)
  (reagent_logged r4)
  (analysis_done s4 r4)
  (reagent_logged r5)
  (analysis_done s5 r5)
 ))
)
