(define (problem 4obs_4sat_4mod)
 (:domain satellite)
 (:objects
  instrument4 instrument5 instrument2 instrument3 instrument1 instrument6 instrument0 - instrument
  satellite0 satellite1 satellite2 satellite3 - satellite
  spectrograph2 thermograph1 image0 infrared3 - mode
  star1 star0 planet2 phenomenon3 planet4 star5 - direction
 )
 (:init
  (supports instrument0 infrared3)
  (supports instrument0 spectrograph2)
  (supports instrument0 image0)
  (calibration_target instrument0 star1)
  (supports instrument1 image0)
  (calibration_target instrument1 star1)
  (on_board instrument0 satellite0)
  (on_board instrument1 satellite0)
  (power_avail satellite0)
  (pointing satellite0 star1)
  (supports instrument2 thermograph1)
  (supports instrument2 infrared3)
  (calibration_target instrument2 star1)
  (on_board instrument2 satellite1)
  (power_avail satellite1)
  (pointing satellite1 star1)
  (supports instrument3 infrared3)
  (supports instrument3 thermograph1)
  (supports instrument3 image0)
  (calibration_target instrument3 star1)
  (supports instrument4 thermograph1)
  (supports instrument4 image0)
  (supports instrument4 infrared3)
  (calibration_target instrument4 star0)
  (on_board instrument3 satellite2)
  (on_board instrument4 satellite2)
  (power_avail satellite2)
  (pointing satellite2 planet2)
  (supports instrument5 image0)
  (calibration_target instrument5 star0)
  (supports instrument6 infrared3)
  (calibration_target instrument6 star0)
  (on_board instrument5 satellite3)
  (on_board instrument6 satellite3)
  (power_avail satellite3)
  (pointing satellite3 star5)
 )
 (:goal (and
  (have_image planet2 image0)
  (have_image phenomenon3 thermograph1)
  (have_image planet4 thermograph1)
  (have_image star5 thermograph1)
 ))
)
