(define (problem 5obs_5sat_5mod)
 (:domain satellite)
 (:objects
  instrument4 instrument5 instrument2 instrument3 instrument1 instrument6 instrument0 - instrument
  satellite2 satellite1 satellite4 satellite0 satellite3 - satellite
  infrared3 infrared2 image1 spectrograph0 image4 - mode
  groundstation0 star1 phenomenon5 planet2 planet6 planet4 phenomenon3 - direction
 )
 (:init
  (supports instrument0 image1)
  (supports instrument0 image4)
  (calibration_target instrument0 groundstation0)
  (on_board instrument0 satellite0)
  (power_avail satellite0)
  (pointing satellite0 groundstation0)
  (supports instrument1 infrared3)
  (supports instrument1 image4)
  (calibration_target instrument1 groundstation0)
  (supports instrument2 spectrograph0)
  (supports instrument2 image1)
  (calibration_target instrument2 star1)
  (on_board instrument1 satellite1)
  (on_board instrument2 satellite1)
  (power_avail satellite1)
  (pointing satellite1 phenomenon5)
  (supports instrument3 infrared2)
  (supports instrument3 image1)
  (supports instrument3 image4)
  (calibration_target instrument3 groundstation0)
  (on_board instrument3 satellite2)
  (power_avail satellite2)
  (pointing satellite2 planet6)
  (supports instrument4 infrared2)
  (supports instrument4 image4)
  (calibration_target instrument4 star1)
  (supports instrument5 image1)
  (supports instrument5 spectrograph0)
  (calibration_target instrument5 groundstation0)
  (on_board instrument4 satellite3)
  (on_board instrument5 satellite3)
  (power_avail satellite3)
  (pointing satellite3 planet2)
  (supports instrument6 infrared3)
  (calibration_target instrument6 star1)
  (on_board instrument6 satellite4)
  (power_avail satellite4)
  (pointing satellite4 planet4)
 )
 (:goal (and
  (have_image planet2 infrared2)
  (have_image phenomenon3 image1)
  (have_image planet4 infrared2)
  (have_image phenomenon5 image4)
  (have_image planet6 spectrograph0)
 ))
)
