from __future__ import annotations

import json
from pathlib import Path

from scripts.run_final_paper_data import (
	format_comparison_latex_macros,
	load_final_paper_manifest,
	validate_final_paper_package,
	write_final_paper_configs,
)
from domain_level_planning.architecture_contract import (
	architecture_gap_summary,
	domain_level_architecture_contract,
)


def test_write_final_paper_configs_uses_artifact_only_manifest(tmp_path: Path) -> None:
	manifest = _artifact_manifest(tmp_path)

	package = write_final_paper_configs(tmp_path, manifest=manifest)

	assert set(package["config_paths"]) == {"main", "ablation", "limitation"}
	for path_text in package["config_paths"].values():
		config = json.loads(Path(path_text).read_text(encoding="utf-8"))
		assert config["experiments"] == []
	assert json.loads((tmp_path / "artifact-manifest.json").read_text(encoding="utf-8"))[
		"artifact_id"
	] == "unit-test-artifact"


def test_validate_final_paper_package_accepts_artifact_only_outputs(
	tmp_path: Path,
) -> None:
	manifest = _artifact_manifest(tmp_path)
	write_final_paper_configs(tmp_path, manifest=manifest)
	_write_minimal_artifact_outputs(tmp_path, manifest)

	validation = validate_final_paper_package(tmp_path, manifest=manifest)

	assert validation["check_count"] > 0


def test_format_comparison_latex_macros_is_artifact_only() -> None:
	assert format_comparison_latex_macros(
		{"report_count": 0, "baseline_count": 0, "paper_table_rows": []},
	) == (
		"% Auto-generated by scripts/run_final_paper_data.py.\n"
		"% Current artifact-only package contains no experiment matrix rows.\n"
	)


def test_load_final_paper_manifest_reads_tracked_contract() -> None:
	manifest = load_final_paper_manifest()

	assert manifest["paper_scope"] == "achievement_goal_atomic_templates_with_temporal_extended_goal_wrappers"
	assert manifest["expected_package"]["report_count"] == 0
	assert manifest["expected_package"]["baseline_count"] == 0


def _artifact_manifest(tmp_path: Path) -> dict[str, object]:
	policy_file = tmp_path / "policy.readable"
	policy_file.write_text(
		"""
		precedence : (1, 1, 0, 0)
		      vars : car0 location0
		    s_cond : (at-ferry location0) (on car0)
		    g_cond : (at car0 location0)
		   actions : (debark car0 location0)
		""",
		encoding="utf-8",
	)
	return {
		"artifact_id": "unit-test-artifact",
		"schema_version": 1,
		"expected_package": {
			"report_count": 0,
			"baseline_count": 0,
			"paper_table_row_count": 0,
		},
		"atomic_artifact_smoke": {
			"backend": "moose",
			"domain_name": "ferry",
			"readable_policy": str(policy_file),
			"source_name": "unit-policy",
		},
		"matrix_configs": {
			"main": {"file": "configs/main-library-matrix.json", "matrix_name": "main"},
			"ablation": {"file": "configs/ablation-matrix.json", "matrix_name": "ablation"},
			"limitation": {"file": "configs/limitation-matrix.json", "matrix_name": "limitation"},
		},
	}


def _write_minimal_artifact_outputs(output_dir: Path, manifest: dict[str, object]) -> None:
	(output_dir / "backend-audit").mkdir(parents=True, exist_ok=True)
	(output_dir / "backend-audit" / "gp-backend-status.txt").write_text("ok\n", encoding="utf-8")
	(output_dir / "comparison.json").write_text(
		json.dumps(
			{
				"report_count": 0,
				"baseline_count": 0,
				"paper_table_rows": [],
				"artifact_mode": "atomic_template_temporal_append",
			},
		),
		encoding="utf-8",
	)
	(output_dir / "artifact-summary.json").write_text(
		json.dumps(
			{
				"artifact_mode": "atomic_template_temporal_append",
				"architecture_gap_summary": architecture_gap_summary(
					domain_level_architecture_contract().gaps,
				),
				"runtime_full_trace_planner": False,
			},
		),
		encoding="utf-8",
	)
	smoke = dict(manifest["atomic_artifact_smoke"])
	atomic_dir = output_dir / "atomic-artifacts" / str(smoke["domain_name"])
	atomic_dir.mkdir(parents=True, exist_ok=True)
	(atomic_dir / "atomic_library_metadata.json").write_text(
		json.dumps(
			{
				"backend": smoke["backend"],
				"compiled_singleton_rule_count": 1,
			},
		),
		encoding="utf-8",
	)
