(define (domain labworkflow)
 (:requirements :strips :typing)
 (:types sample reagent - object)
 (:predicates
  (sample_available ?s - sample)
  (reagent_available ?r - reagent)
  (reagent_logged ?r - reagent)
  (analysis_done ?s - sample ?r - reagent)
 )
 (:action log_reagent
  :parameters (?r - reagent)
  :precondition (reagent_available ?r)
  :effect (reagent_logged ?r)
 )
 (:action run_analysis
  :parameters (?s - sample ?r - reagent)
  :precondition (and (sample_available ?s) (reagent_available ?r))
  :effect (and (analysis_done ?s ?r) (not (reagent_available ?r)))
 )
)
